### ISSUE TITLE
License Request

### ISSUE THREAD

**Issue by jfullstackdev** [janbodnar/Java-Tetris-Game#1]
Good day, @janbodnar.

This repository is good and can be developed further. However, I can't do that because there is no specific license here, which means, in GitHub rules, a read-only repository. Also, I can't use this in my lessons without your permission.

May I just request if you can put a license in this repo. 

Thank you so much.

**Comment by janbodnar** [comment]
Hi, licence added.

**Comment by jfullstackdev** [comment]
Thanks a lot! I'll fork this repo and will add this license.
