### ISSUE TITLE
What JDK?

### ISSUE THREAD

**Issue by MarkusMCGO** [janbodnar/Java-Tetris-Game#3]
im using jdk 14 but it says var cant be resloveled. i tried jdk 8, 12 ,10 and 11 but none work.

**Comment by janbodnar** [comment]
If you are using IntelliJ IDEA, then you need to set the correct version of Java in project properties and settings. The IDE for some reason defaults to older Java by default.

**Comment by MarkusMCGO** [comment]
Thanks!
